export const APP_NAME = "safespace-mobile-server";

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CENTRAL_UNIT_AUTH_FAILED: "CENTRAL_UNIT_AUTH_FAILED",
};

